name: Draft Release PR
on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  draft-release:
    name: Draft Release PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Create Draft Release PR
        uses: pantheon-systems/plugin-release-actions/release-pr@c661c8c4d4b5034ba3bc39c4da62c37a7bb547c4 # main 2025-11-07T23:23:14Z
        with:
          gh_token: ${{ github.token }}
          readme_md: README.md
