name: Shellcheck
on:
  push:
    paths:
      - 'bin/*.sh'
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Shellcheck
        run: find bin/ -name "*.sh" | grep -v "install-wp-tests.sh" | xargs shellcheck
